"""Event-VM control-flow model — the engine's text-reachability graph.

The single source of truth for "what does the event VM read, and where can it jump."
`text/config/opcode_spec.json` (generated by the canonical build_opcode_spec tool from the Ghidra
handlers) encodes per-opcode: `len` (operand words), `ptr` (which operand words are
stream pointers), `var` (variable choice/list layout), `ink`, line/page reset. This
module turns that spec into a walkable graph so extraction and remapping follow the
engine's actual flow instead of a linear byte-scan (tr.extract_story_vm) or a heuristic
pointer-pair scan (scriptrefs.scan_pairs).

EDGE MODEL (verified against the live handlers 2026-06-22):
  * Fixed op at A: for each HI-word index i in spec["ptr"],
        target = (word(A+2+2*i) << 16) | word(A+2+2*(i-1))      # lo at i-1, hi at i
  * Var op 0x313 ScriptOp_Choice (0x08134900): header len=1; num_rows=(countword>>8)+1;
        rows stride 3 = [param, lo, hi].
  * Var op 0x413 Negotiate_SelectResponse (0x081386DC): header len=1; same count;
        rows stride 2 = [lo, hi].
  NB the asymmetry: fixed spec["ptr"] indexes the HI word; var row_ptr indexes the LO word.
  * 0x0301 ScriptOp_EndMessage is a RETURN/POP off a 5-deep gosub stack (it does NOT fall
    through to the next word); 0x0000 ends the stream. A reachability walk stops at either.
"""
from __future__ import annotations

import json
from collections import deque
import rom_layout as rommap
from paths import ProjectPaths

ROM_BASE = 0x08000000

_DATA = ProjectPaths.discover().text_config_root
SPEC = {int(k, 16): v for k, v in
        json.loads((_DATA / "opcode_spec.json").read_text(encoding="utf-8")).items()}

# substitution / control tokens that are not glyphs and not pointer-carrying opcodes
STOK = {0x0300, 0x0316, 0x0317, 0x031A, 0x031B, 0x031C, 0x031D, 0x036E}


def u16(rom, a):
    o = a - ROM_BASE
    return rom[o] | (rom[o + 1] << 8)


def edges_at(rom, a):
    """(targets, op_byte_size) for the opcode at `a` per the verified edge model.
    (None, None) if `a` does not hold an opcode."""
    c = u16(rom, a)
    if not (rommap.OP_LO <= c <= rommap.VMCTRL_HI):
        return None, None
    spec = SPEC.get(c)
    if spec is None:
        return [], 2
    tgts = []
    var = spec.get("var")
    if var:
        hdr = spec["len"]
        countword = u16(rom, a + 2 + 2 * var["count_word"])
        nrows = (countword >> 8) + 1
        stride = var["stride"]
        lo_idx = var["row_ptr"][0]                      # row_ptr indexes the LO word
        row0 = a + 2 + 2 * hdr
        for r in range(nrows):
            base = row0 + r * stride * 2
            tgts.append((u16(rom, base + 2 * lo_idx + 2) << 16) | u16(rom, base + 2 * lo_idx))
        return tgts, 2 + 2 * hdr + nrows * stride * 2
    for i in spec["ptr"]:                               # fixed: ptr indexes the HI word
        tgts.append((u16(rom, a + 2 + 2 * i) << 16) | u16(rom, a + 2 + 2 * (i - 1)))
    return tgts, 2 + 2 * spec["len"]


def walk_stream(rom, start, lo, hi, glyph_map, max_words=4000):
    """Walk one VM stream from `start`: follow opcodes (collecting in-bank pointer edges)
    and glyph/control words; stop at a terminator or the first non-text / non-op word.
    Returns (in_bank_edge_targets, glyph_count)."""
    a, tgts, glyphs, n = start, [], 0, 0
    while lo <= a < hi and n < max_words:
        n += 1
        c = u16(rom, a)
        if c in (rommap.TERM_MSG, rommap.TERM_NUL):
            break
        if c in STOK or c == rommap.PAD_WORD:
            a += 2
            continue
        if rommap.OP_LO <= c <= rommap.VMCTRL_HI:
            es, size = edges_at(rom, a)
            tgts.extend(t for t in es if lo <= t < hi and not (t & 1))
            a += size
            continue
        if c in glyph_map:
            glyphs += 1
            a += 2
            continue
        break
    return tgts, glyphs


def reachable(rom, lo, hi, roots, glyph_map):
    """BFS the control-flow graph from `roots`. Returns
    (visited_stream_starts, edge_targets, edge_src{target: a_source_stream})."""
    visited, edge_targets, edge_src = set(), set(), {}
    q = deque(r for r in roots if lo <= r < hi)
    while q:
        a = q.popleft()
        if a in visited:
            continue
        visited.add(a)
        for t in walk_stream(rom, a, lo, hi, glyph_map)[0]:
            edge_src.setdefault(t, a)
            if t not in edge_targets:
                edge_targets.add(t)
                q.append(t)
    return visited, edge_targets, edge_src


def first_glyph(rom, a, lo, hi, glyph_map, limit=24):
    """First real prose glyph at/after `a`, skipping a leading control/op/optail/pad
    prefix (a jump often targets a few control words before the prose). None if the
    run hits a terminator or non-text word first."""
    n = 0
    while lo <= a < hi and n < limit:
        n += 1
        c = u16(rom, a)
        if c in (rommap.TERM_MSG, rommap.TERM_NUL):
            return None
        if c in glyph_map and not (rommap.OPTAIL_LO <= c <= rommap.OPTAIL_HI):
            return a
        if (c in STOK or c == rommap.PAD_WORD or rommap.OP_LO <= c <= rommap.VMCTRL_HI
                or rommap.OPTAIL_LO <= c <= rommap.OPTAIL_HI):
            a += 2
            continue
        return None
    return None


def prose_start(rom, t, lo, hi, glyph_map, need=5, window=28):
    """Address where the first contiguous prose run of >=`need` glyphs begins at/after `t`,
    skipping a leading dispatch prefix (cond-jump chains, pointer-half symbols, ops). This
    is where a real MESSAGE starts — `first_glyph` instead stops at the first stray glyph,
    which for branch targets is often a pointer lo-half symbol. None if no run / hit a
    terminator first."""
    ws, a = [], t
    for _ in range(window):
        if not (lo <= a < hi):
            break
        c = u16(rom, a)
        if c in (rommap.TERM_MSG, rommap.TERM_NUL):
            break
        ws.append(c)
        a += 2
    for i in range(len(ws) - need + 1):
        if all(_is_prose_word(ws[i + j], glyph_map) for j in range(need)):
            return t + 2 * i
    return None


def _is_prose_word(c, glyph_map):
    return (c in glyph_map and not (rommap.OPTAIL_LO <= c <= rommap.OPTAIL_HI)
            and not (rommap.OP_LO <= c <= rommap.VMCTRL_HI) and c not in STOK
            and c not in (rommap.TERM_MSG, rommap.TERM_NUL, rommap.PAD_WORD))


def is_leaf_message(rom, g, glyph_map, need=5, window=24):
    """True if `g` begins a real leaf MESSAGE (a contiguous prose run of >=`need`
    glyphs within the first `window` words), vs a dispatch/choice block whose CJK are
    isolated pointer-halves between opcodes."""
    run = best = 0
    for k in range(window):
        if _is_prose_word(u16(rom, g + 2 * k), glyph_map):
            run += 1
            best = max(best, run)
        else:
            run = 0
    return best >= need


def build_refmap(rom):
    """value(even in-ROM ptr) -> [ref-site addrs]. One 4-aligned scan subsumes pointer-
    table slots AND `ldr` literal-pool entries (a structural pointer is structural either way)."""
    n = len(rom)
    refs = {}
    for o in range(0, n - 3, 4):
        v = int.from_bytes(rom[o:o + 4], "little")
        if ROM_BASE <= v < ROM_BASE + n and not (v & 1):
            refs.setdefault(v, []).append(ROM_BASE + o)
    return refs


def _is_cjk(ch):
    return any(0x3040 <= ord(c) <= 0x30FF or 0x4E00 <= ord(c) <= 0x9FFF for c in ch)


def message_run(rom, g, glyph_map, maxw=220):
    """Decode the run at `g` to its terminator. Returns (prose_text, ok). `ok` is the
    content gate (replaces dump/audit_orphans.looks_like_text so vmflow is self-contained):
    >=80% of words decode (glyph/control/pad), and the non-optail CJK content is >=2 glyphs
    and >=25% of the glyphs — rejecting op/pointer-half-heavy dispatch debris and dot runs."""
    codes, a = [], g
    while a < g + 2 * maxw:
        c = u16(rom, a)
        if c in (rommap.TERM_MSG, rommap.TERM_NUL):
            break
        codes.append(c)
        a += 2
    if len(codes) < 4:
        return "", False
    glyphs = [c for c in codes if c in glyph_map]
    decod = [c for c in codes if (c in glyph_map or 0x0300 <= c <= 0x031B or c == rommap.PAD_WORD)]
    if not glyphs or len(decod) / len(codes) < 0.80:
        return "", False
    content = [c for c in glyphs
               if not (rommap.OPTAIL_LO <= c <= rommap.OPTAIL_HI) and _is_cjk(glyph_map[c])]
    if len(content) < 2 or len(content) / len(glyphs) < 0.25:
        return "", False
    text = "".join(glyph_map[c] for c in glyphs if not (rommap.OPTAIL_LO <= c <= rommap.OPTAIL_HI))
    return text, True


def find_leaf_gaps(rom, lo, hi, glyph_map, owned, claimed_starts):
    """Leaf MESSAGE gaps in [lo,hi): text reachable by VM jump/choice that no Section owns.
    Roots = claimed entry starts UNION structural pointer/literal sites (refmap targets with
    a ref-site outside `owned`). Returns dicts {addr (clean prose start), text, glyphs, n
    (entry points), via (a source stream)}, deduped by leading text — the unit a translator
    edits. Shared by the extractor (additive capture) and audit_reachability.py."""
    refs = build_refmap(rom)
    ext = {t for t, sites in refs.items() if lo <= t < hi and any(s not in owned for s in sites)}
    _v, edge_targets, edge_src = reachable(rom, lo, hi, claimed_starts | ext, glyph_map)

    def claimed(a):
        return any((a + d) in owned for d in (0, 2, 4, 6))

    by_text, out = {}, []
    for t in sorted(edge_targets):
        if claimed(t):
            continue
        g = prose_start(rom, t, lo, hi, glyph_map)        # start of the actual sentence
        if g is None or claimed(g):
            continue
        text, ok = message_run(rom, g, glyph_map)
        if not ok:
            continue
        key = text[:16]
        if key in by_text:
            by_text[key]["n"] += 1
            continue
        row = {"addr": g, "text": text, "glyphs": sum(1 for _ in text),
               "n": 1, "via": edge_src.get(t, 0)}
        by_text[key] = row
        out.append(row)
    return out
